[package]
name = "strategies-core"
version = "0.2.2"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
rayon.workspace = true
thiserror.workspace = true
indicators-core = { path = "../indicators" }
factors-core = { path = "../factors" }
inventory = "0.3"
strategies-proc-macro = { path = "proc-macro" }
napi = { workspace = true, optional = true }
napi-derive = { workspace = true, optional = true }
schemars = { workspace = true, features = ["derive"] }

[features]
napi = ["dep:napi", "dep:napi-derive"]
