[package]
name = "factors-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
napi = { workspace = true, optional = true }
napi-derive = { workspace = true, optional = true }

[features]
napi = ["dep:napi", "dep:napi-derive"]
