import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

interface RegistryJson {
	version: number
	factors: Record<string, FactorEntry>
	indicators: Record<string, IndicatorEntry>
	strategies: Record<string, StrategyEntry>
}

interface FactorEntry {
	id: string
	name: string
	category: string
	description: string
	needs_prices: boolean
	output_type: string
}

interface IndicatorEntry {
	id: string
	name: string
	category: string
	description: string
	output_type: string
}

interface StrategyEntry {
	id: string
	name: string
	category: string
	default_timeframes: string[]
	description: string
	defaults: Record<string, unknown>
	output_type: string
}

function inferZodType(value: unknown): string {
	if (value === null || value === undefined) return 'z.unknown()'
	if (typeof value === 'number') {
		return Number.isInteger(value) ? 'z.number().int()' : 'z.number()'
	}
	if (typeof value === 'boolean') return 'z.boolean()'
	if (typeof value === 'string') return 'z.string()'
	if (Array.isArray(value)) {
		if (value.length === 0) return 'z.array(z.unknown())'
		const elemTypes = new Set(value.map(inferZodType))
		const elemType = elemTypes.size === 1 ? [...elemTypes][0] : 'z.unknown()'
		return `z.array(${elemType})`
	}
	if (typeof value === 'object' && value !== null) {
		const entries = Object.entries(value as Record<string, unknown>)
		if (entries.length > 0) {
			const fields = entries.map(([k, v]) => `${k}: ${inferZodType(v)}`)
			const joined = fields.join(', ')
			return `z.object({ ${joined} })`
		}
		return 'z.record(z.string(), z.unknown())'
	}
	return 'z.unknown()'
}

function generateConfigSchema(defaults: Record<string, unknown>): string {
	const keys = Object.keys(defaults)
	if (keys.length === 0) return 'z.object({}).optional()'

	const fields = keys.map((key) => {
		const value = defaults[key]
		const zodType = inferZodType(value)
		const jsonValue = JSON.stringify(value)
		return `${key.replace(/[^a-zA-Z0-9_$]/g, '_')}: ${zodType}.optional().default(${jsonValue})`
	})

	const joined = fields.join(', ')
	return `z.object({ ${joined} }).optional()`
}

function capitalize(s: string): string {
	return s.charAt(0).toUpperCase() + s.slice(1)
}

function main() {
	const registryPath = resolve(import.meta.dirname, '../src/generated/registry.json')
	const registry: RegistryJson = JSON.parse(readFileSync(registryPath, 'utf-8'))

	const lines: string[] = []
	lines.push('// Auto-generated by packages/tools/scripts/generate.ts — do not edit manually')
	lines.push('')
	lines.push("import { z } from 'zod'")
	lines.push("import { createWorkflowTool } from '../tool'")
	lines.push("import type { WorkflowTool, ToolResult } from '../types'")
	lines.push('')
	lines.push('// ── Registry data ────────────────────────────────────────')
	lines.push('')
	lines.push(`export const registryVersion = ${registry.version}`)
	lines.push('')

	// Export factors
	lines.push(`export const factorCount = ${Object.keys(registry.factors).length}`)
	lines.push(`export const indicatorCount = ${Object.keys(registry.indicators).length}`)
	lines.push(`export const strategyCount = ${Object.keys(registry.strategies).length}`)

	lines.push('')
	lines.push('export const registryData = {\n  factors: {')
	for (const [id, entry] of Object.entries(registry.factors)) {
		lines.push(`    "${id}": ${JSON.stringify(entry)},`)
	}
	lines.push('  } as const,')
	lines.push('  indicators: {')
	for (const [id, entry] of Object.entries(registry.indicators)) {
		lines.push(`    "${id}": ${JSON.stringify(entry)},`)
	}
	lines.push('  } as const,')
	lines.push('  strategies: {')
	for (const [id, entry] of Object.entries(registry.strategies)) {
		const { defaults, ...meta } = entry
		lines.push(`    "${id}": { ${JSON.stringify(meta).slice(1, -1)}, defaults: ${JSON.stringify(defaults)} },`)
	}
	lines.push('  } as const,')
	lines.push('}')

	lines.push('')
	lines.push('// ── Factor tools ────────────────────────────────────────')
	lines.push('')

	const factorIds = Object.keys(registry.factors)
	lines.push('export function createStrategyTools(')
	lines.push('  execute: (id: string, params:')
	lines.push('    { closes: number[]; highs?: number[]; lows?: number[]; volumes?: number[]; config?: Record<string, unknown> }')
	lines.push('  ) => Promise<ToolResult>,')
	lines.push('): WorkflowTool[] {')
	lines.push('  const tools: WorkflowTool[] = []')
	lines.push('')

	// Generate strategy tools
	for (const [id, entry] of Object.entries(registry.strategies)) {
		const safeName = entry.id.replace(/[^a-zA-Z0-9_$]/g, '_')
		const configSchema = generateConfigSchema(entry.defaults as Record<string, unknown>)
		lines.push(`  // ${entry.name} (${entry.category})`)
		lines.push(`  tools.push(createWorkflowTool({`)
		lines.push(`    name: "${safeName}",`)
		lines.push(`    description: ${JSON.stringify(entry.description)} + " (returns: ${entry.output_type})",`)
		lines.push(`    parameters: z.object({`)
		lines.push(`      closes: z.array(z.number()).describe("Array of closing prices (oldest first)"),`)
		lines.push(`      highs: z.array(z.number()).optional().describe("Array of high prices"),`)
		lines.push(`      lows: z.array(z.number()).optional().describe("Array of low prices"),`)
		lines.push(`      volumes: z.array(z.number()).optional().describe("Array of volume data"),`)
		lines.push(`      config: ${configSchema}.describe("Strategy configuration parameters"),`)
		lines.push(`    }),`)
		lines.push(`    execute: async (params) => execute("${id}", params),`)
		lines.push(`  }))`)
		lines.push('')
	}

	lines.push('  return tools')
	lines.push('}')
	lines.push('')

	// Generate indicator tools
	lines.push('// ── Indicator tools ──────────────────────────────────────')
	lines.push('')
	lines.push('export function createIndicatorTools(')
	lines.push('  execute: (id: string, params: { values: number[]; config?: Record<string, unknown> }) => Promise<ToolResult>,')
	lines.push('): WorkflowTool[] {')
	lines.push('  const tools: WorkflowTool[] = []')
	lines.push('')
	for (const [id, entry] of Object.entries(registry.indicators)) {
		const safeName = entry.id.replace(/[^a-zA-Z0-9_$]/g, '_')
		lines.push(`  tools.push(createWorkflowTool({`)
		lines.push(`    name: "${safeName}",`)
		lines.push(`    description: ${JSON.stringify(entry.description)} + " (returns: ${entry.output_type})",`)
		lines.push(`    parameters: z.object({`)
		lines.push(`      values: z.array(z.number()).describe("Array of input values (oldest first)"),`)
		lines.push(`    }),`)
		lines.push(`    execute: async (params) => execute("${id}", params),`)
		lines.push(`  }))`)
		lines.push('')
	}

	lines.push('  return tools')
	lines.push('}')
	lines.push('')

	// Generate factor tools
	lines.push('// ── Factor tools ────────────────────────────────────────')
	lines.push('')

	lines.push('export function createFactorTools(')
	lines.push('  execute: (id: string, params: { fundamentals: unknown[]; prices?: unknown[] }) => Promise<ToolResult>,')
	lines.push('): WorkflowTool[] {')
	lines.push('  const tools: WorkflowTool[] = []')
	lines.push('')

	for (const [id, entry] of Object.entries(registry.factors)) {
		const safeName = entry.id.replace(/[^a-zA-Z0-9_$]/g, '_')
		const needsPrices = entry.needs_prices ? 'optional()' : 'optional()'
		lines.push(`  tools.push(createWorkflowTool({`)
		lines.push(`    name: "${safeName}",`)
		lines.push(`    description: ${JSON.stringify(entry.description)} + " (returns: ${entry.output_type})",`)
		lines.push(`    parameters: z.object({`)
		lines.push(`      fundamentals: z.array(z.unknown()).describe("Fundamental data points"),`)
		if (entry.needs_prices) {
			lines.push(`      prices: z.array(z.unknown()).optional().describe("OHLCV price bars"),`)
		}
		lines.push(`    }),`)
		lines.push(`    execute: async (params) => execute("${id}", params),`)
		lines.push(`  }))`)
		lines.push('')
	}

	lines.push('  return tools')
	lines.push('}')
	lines.push('')

	const outputPath = resolve(import.meta.dirname, '../src/generated/tools.ts')
	writeFileSync(outputPath, lines.join('\n'), 'utf-8')
	console.log(`Wrote ${Object.keys(registry.strategies).length} strategy tools, ${Object.keys(registry.indicators).length} indicator tools, ${Object.keys(registry.factors).length} factor tools to ${outputPath}`)
}

main()
