// ── Strategies ──────────────────────────────────────
// Auto-generated #[napi] bindings from #[strategy] macro
pub use strategies_core::{
	// Strategy registry and execution
	registry::{get_strategy_descriptors, get_strategy_registry_impl, StrategyInput},
	// Re-export all auto-generated NAPI binding functions
	// (generated by #[strategy] macro with #[napi] annotation)
};

// ── Factors ─────────────────────────────────────────
// Core factors already have #[cfg_attr(feature = "napi", napi)] on pub functions
pub use factors_core::{
	registry::{get_factor_descriptors, get_factor, FactorDescriptor},
};

// ── Indicators ──────────────────────────────────────
// Core indicators do NOT have #[napi] on functions, only on config/result structs
// For NAPI bindings, import from the existing indicators-napi binding crate
// (or add wrappers here in a future pass)

// ── Combined registry ───────────────────────────────
use napi_derive::napi;

#[napi]
pub fn init() -> f64 {
	0.1
}

#[napi(object)]
pub struct RegistryCounts {
	pub factors: u32,
	pub indicators: u32,
	pub strategies: u32,
}

#[napi]
pub fn get_registry_counts() -> RegistryCounts {
	RegistryCounts {
		factors: factors_core::registry::get_factor_descriptors().len() as u32,
		indicators: indicators_core::registry::get_indicator_descriptors().len() as u32,
		strategies: strategies_core::registry::get_strategy_descriptors().len() as u32,
	}
}
