[package]
name = "strategies"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
strategies-core = { path = "../../crates/strategies", features = ["napi"] }
indicators-core = { path = "../../crates/indicators", features = ["napi"] }
factors-core = { path = "../../crates/factors", features = ["napi"] }
napi.workspace = true
napi-derive.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
napi-build.workspace = true

[dev-dependencies]
strategies = { path = "." }

