[package]
name = "quantamental"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
factors = { path = "../factors-napi" }
indicators = { path = "../indicators-napi" }
strategies = { path = "../strategies-napi" }
napi.workspace = true
napi-derive.workspace = true

[build-dependencies]
napi-build.workspace = true
