#!/usr/bin/env python3
"""Standalone Binance USDⓈ-M futures OHLCV pipeline.

Replaces the old postgres ``price_bars`` loader so the traditional-
strategy screens run with zero external infra.  Same contract as the old
``pg_loader``::

    from binance_loader import load_price_bars, coverage_report
    data = load_price_bars("2023-01-01", "2026-08-01", tf="1h")

returns ``{canonical_symbol: polars.DataFrame}`` with columns
``timestamp`` (ms epoch Int64) / ``open`` / ``high`` / ``low`` / ``close`` /
``volume`` (Float32), sorted, symbols ≥ 50 rows dropped — the exact shape
``screen.load_universe`` and friends expect.

Data flow
---------
- **Universe** — ``config/symbols.yaml`` (canonical ``{BASE}/USDT:PERP``
  spelling, generated by ``config/symbols-sync.py``): the top Binance-Futures
  USDT perpetuals by market cap.  Override with ``--universe FILE`` (one
  canonical symbol per line, comments/blank ok).
- **Deep backfill** — ``data.binance.vision`` monthly 1m klines zips
  (``data/futures/um/monthly/klines``), which cover symbol history from
  listing day and are free of rate limits.  Missing months are fetched
  individually; a 404 means the symbol was not listed that month (legal).
- **Tail refresh** — Binance Futures REST ``/fapi/v1/klines`` (1m, 1500/req,
  paginated) from the newest cached bar to now.  This is the daily
  incremental path (``--update``) and the catch-up path after a backfill.
- **Storage** — one parquet per symbol at ``data/{BASEUSDT}.parquet`` (1m,
  ms-epoch timestamps).  The parquet *is* the checkpoint: coverage is
  inferred from it, so everything is resumable/idempotent.
- **Resample** — ``load_price_bars`` resamples 1m → tf in polars with the
  same epoch-aligned-bucket semantics the old SQL used (open=first, high=max,
  low=min, close=last, volume=sum; partial boundary buckets < the expected
  1m-bar count are dropped unless ``drop_partial=False``).

Usage::

    uv run python binance_loader.py --sync                # full hydration (vision + REST tail)
    uv run python binance_loader.py --sync --start 2023-01-01
    uv run python binance_loader.py --update              # REST-only tail refresh
"""

from __future__ import annotations

import io
import json
import os
import sys
import time
import urllib.error
import urllib.request
import zipfile
from datetime import datetime, timezone

import polars as pl

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")
CONFIG_DIR = os.path.join(HERE, "config")
DEFAULT_UNIVERSE = os.path.join(CONFIG_DIR, "symbols.yaml")

_SYMBOLS_PATH = DEFAULT_UNIVERSE

VISION = "https://data.binance.vision/data/futures/um/monthly/klines"
FAPI = "https://fapi.binance.com/fapi/v1"
KLINES_LIMIT = 1500
MIN_ROWS = 50  # symbols with fewer bars than this are dropped, as pg_loader did

# canonical symbol -> fapi symbol ("BTC/USDT:PERP" -> "BTCUSDT")
_BAR_MS = {
    "1m": 60_000,
    "15m": 900_000,
    "30m": 1_800_000,
    "1h": 3_600_000,
    "4h": 14_400_000,
    "12h": 43_200_000,
    "1d": 86_400_000,
}

# 1m klines: open_time, open, high, low, close, volume, close_time,
# quote_volume, count, taker_buy_volume, taker_buy_quote_volume, ignore
_KLINE_COLS = [
    "timestamp",
    "open",
    "high",
    "low",
    "close",
    "volume",
]


def _ms(s: str) -> int:
    return int(
        datetime.strptime(s, "%Y-%m-%d").replace(tzinfo=timezone.utc).timestamp() * 1000
    )


def _now_ms() -> int:
    return int(time.time() * 1000)


def _cache_path(api: str) -> str:
    os.makedirs(DATA_DIR, exist_ok=True)
    return os.path.join(DATA_DIR, f"{api}.parquet")


# ── universe ────────────────────────────────────────────────────────────────


def symbols(universe: str | None = None) -> list[str]:
    """Canonical symbol list from symbols.yaml (or a plain-text override:
    one canonical symbol per line, blank/# lines ignored), sorted."""
    path = universe or _SYMBOLS_PATH
    if not os.path.exists(path):
        sys.exit(
            f"no universe file at {path} — run config/symbols-sync.py first "
            "(writes config/symbols.yaml) or pass --universe FILE"
        )
    canon: set[str] = set()
    with open(path) as fh:
        for ln in fh:
            ln = ln.split("#")[0].strip()
            if ln.startswith("-"):  # yaml list marker "- "SYM/USDT:PERP""
                ln = ln[1:].strip()
            ln = ln.strip('"').strip("'").strip()
            if ln and "/USDT:PERP" in ln:
                canon.add(ln)
    return sorted(canon)


def _api(canon: str) -> str:
    return canon.split("/")[0] + "USDT"


def _canon(api: str) -> str:
    return api[: -len("USDT")] + "/USDT:PERP"


# ── low-level fetching ──────────────────────────────────────────────────────


def _fetch(url: str, retries: int = 3) -> bytes:
    last: Exception | None = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(
                url, headers={"User-Agent": "qtm-traditional/0.1"}
            )
            with urllib.request.urlopen(req, timeout=60) as resp:
                return resp.read()
        except urllib.error.HTTPError as e:
            if e.code == 404:
                raise  # symbol not listed that month / unknown — caller decides
            last = e
            if e.code in (429, 418, 5):
                pass  # rate limited — back off below
        except urllib.error.URLError as e:
            last = e
        time.sleep(0.5 * (2**attempt) + 0.25)
    raise RuntimeError(f"fetch failed after {retries} attempts: {url} ({last})")


def _parse_klines_rows(rows) -> pl.DataFrame:
    """REST klines JSON rows or vision CSV rows -> the 1m frame:
    timestamp Int64 ms / OHLCV Float32, minus the 7 trailing kline fields."""
    out = []
    for r in rows:
        out.append(
            (int(r[0]), float(r[1]), float(r[2]), float(r[3]), float(r[4]), float(r[5]))
        )
    df = pl.DataFrame(out, schema=_KLINE_COLS, orient="row")
    return df.with_columns([pl.col(c).cast(pl.Float32) for c in _KLINE_COLS[1:]])


def _mirror_vision_month(api: str, y: int, m: int) -> pl.DataFrame:
    """One data.binance.vision monthly 1m zip -> 1m frame (or empty on 404)."""
    url = f"{VISION}/{api}/1m/{api}-1m-{y:04d}-{m:02d}.zip"
    try:
        raw = _fetch(url)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return pl.DataFrame(schema=_KLINE_COLS)
        raise
    with zipfile.ZipFile(io.BytesIO(raw)) as z:
        name = z.namelist()[0]
        csv = z.read(name).decode()
    rows = [ln.split(",") for ln in csv.strip().splitlines()]
    if rows and rows[0] and rows[0][0] == "open_time":  # vision CSVs carry a header
        rows = rows[1:]
    return _parse_klines_rows(rows)


def _fetch_klines_range(api: str, start_ms: int, end_ms: int) -> pl.DataFrame:
    """REST klines paginated over [start_ms, end_ms) — the incremental tail."""
    frames: list[pl.DataFrame] = []
    cur = start_ms
    while cur < end_ms:
        url = (
            f"{FAPI}/klines?symbol={api}&interval=1m&startTime={cur}"
            f"&limit={KLINES_LIMIT}"
        )
        raw = _fetch(url)
        rows = json.loads(raw)
        if not rows:
            break
        df = _parse_klines_rows(rows)
        frames.append(df)
        nxt = int(rows[-1][0]) + 60_000
        if nxt <= cur:
            break
        cur = nxt
        time.sleep(0.06)  # futures REST limit is 2400 weight/min; klines weight 1
    if not frames:
        return pl.DataFrame(schema=_KLINE_COLS)
    return pl.concat(frames, rechunk=False)


# ── hydration ───────────────────────────────────────────────────────────────


def _covered_months(df: pl.DataFrame) -> set[tuple[int, int]]:
    if df.is_empty():
        return set()
    ts = df["timestamp"].to_numpy()
    # month anchor from the ms epoch, UTC
    months = {
        (
            datetime.fromtimestamp(t / 1000, tz=timezone.utc).year,
            datetime.fromtimestamp(t / 1000, tz=timezone.utc).month,
        )
        for t in ts
    }
    return months


def _month_range(y: int, m: int) -> tuple[int, int]:
    start = datetime(y, m, 1, tzinfo=timezone.utc)
    if m == 12:
        end = datetime(y + 1, 1, 1, tzinfo=timezone.utc)
    else:
        end = datetime(y, m + 1, 1, tzinfo=timezone.utc)
    return int(start.timestamp() * 1000), int(end.timestamp() * 1000)


def hydrate_symbol(canon: str, start: str, end: str, rest_only: bool = False) -> int:
    """Bring one symbol's 1m parquet up to date over [start, end] (inclusive
    of ``end``'s day).  Returns the number of bars added."""
    api = _api(canon)
    path = _cache_path(api)
    existing = pl.read_parquet(path) if os.path.exists(path) else None
    if existing is not None:
        existing = _clean(existing)

    sm, em = _ms(start), _ms(end) + 86_399_999  # end date inclusive, ms day end
    added = 0

    # 1) vision backfill for uncovered months
    if not rest_only:
        covered = _covered_months(existing) if existing is not None else set()
        year, month = (
            datetime.fromtimestamp(sm / 1000, tz=timezone.utc).year,
            datetime.fromtimestamp(sm / 1000, tz=timezone.utc).month,
        )
        parts = []
        if existing is not None:
            parts.append(existing)
        while True:
            ms0, ms1 = _month_range(year, month)
            if ms0 > em or ms0 > _now_ms():
                break
            if (year, month) not in covered and ms1 > sm:
                got = _mirror_vision_month(api, year, month)
                if not got.is_empty():
                    parts.append(got)
                    added += got.height
            if month == 12:
                year, month = year + 1, 1
            else:
                month += 1
    else:
        parts = [existing] if existing is not None else []

    # 2) REST tail: from the newest cached bar (or window start) to now
    combined = _clean(pl.concat(parts, rechunk=False)) if parts else existing
    if combined is None:
        combined = pl.DataFrame(schema=_KLINE_COLS)
    latest = int(combined["timestamp"].max()) if not combined.is_empty() else None
    tail_from = max(sm, (latest + 60_000) if latest is not None else sm)
    if tail_from <= min(_now_ms(), em):
        tail = _fetch_klines_range(api, tail_from, min(_now_ms(), em) + 60_000)
        if not tail.is_empty():
            n0 = combined.height
            combined = _clean(pl.concat([combined, tail], rechunk=False))
            added += combined.height - n0

    combined = combined.filter(
        (pl.col("timestamp") >= sm) & (pl.col("timestamp") <= em)
    )
    if not combined.is_empty():
        combined.write_parquet(path)
    return added


def _clean(df: pl.DataFrame) -> pl.DataFrame:
    """sort/dedup/drop-null on the 1m frame."""
    return (
        df.filter(pl.col("timestamp").is_not_null())
        .unique(subset=["timestamp"], keep="first")
        .sort("timestamp")
    )


def hydrate_all(
    start: str, end: str, rest_only: bool = False, universe: str | None = None
) -> None:
    syms = symbols(universe)
    print(
        f"hydrating {len(syms)} symbols over {start}..{end} "
        f"({'REST tail' if rest_only else 'vision backfill + REST tail'})",
        file=sys.stderr,
        flush=True,
    )
    ok, failed = 0, []
    for i, canon in enumerate(syms, 1):
        try:
            n = hydrate_symbol(canon, start, end, rest_only=rest_only)
            print(f"  {i:3d}/{len(syms)} {canon}: +{n} bars", file=sys.stderr)
            ok += 1
        except Exception as e:  # noqa: BLE001
            failed.append((canon, e))
            print(f"  {i:3d}/{len(syms)} {canon}: FAILED {e}", file=sys.stderr)
    print(f"done: {ok}/{len(syms)} ok, {len(failed)} failed", file=sys.stderr)
    for canon, e in failed:
        print(f"    {canon}: {e}", file=sys.stderr)


# ── the pg_loader-compatible load path ──────────────────────────────────────


def _resample(df: pl.DataFrame, tf: str, drop_partial: bool) -> pl.DataFrame:
    bar = _BAR_MS[tf]
    if bar == _BAR_MS["1m"]:
        return df
    expected = bar // _BAR_MS["1m"]  # 1m bars per bucket (the SQL used bar//60 sec)
    bucket = (pl.col("timestamp") // bar).alias("_b")
    rs = (
        df.with_columns(bucket)
        .group_by(["_b"], maintain_order=True)
        .agg(
            pl.first("open").alias("open"),
            pl.max("high").alias("high"),
            pl.min("low").alias("low"),
            pl.last("close").alias("close"),
            pl.sum("volume").alias("volume"),
            pl.len().alias("_n"),
        )
        .filter(pl.col("_n") >= expected)
        .drop("_n")
        .with_columns((pl.col("_b") * bar).alias("timestamp"))
        .drop("_b")
    )
    rs = rs.with_columns(
        [pl.col(c).cast(pl.Float32) for c in ("open", "high", "low", "close", "volume")]
    )
    return rs.sort("timestamp")


def load_price_bars(
    start: str = "2025-07-01",
    end: str = "2026-08-01",
    tf: str = "1h",
    exchange: str = "binance",
    force: bool = False,
    syms: str | None = None,
    drop_partial: bool = True,
) -> dict[str, pl.DataFrame]:
    """Load OHLCV for the universe, resampled to ``tf`` (15m/30m/1h/4h/12h/1d).

    Mirrors the old postgres loader: epoch-aligned buckets, open=first /
    high=max / low=min / close=last / volume=sum, partial boundary buckets
    dropped, symbols under 50 bars dropped.  Returns
    ``{canonical: DataFrame(timestamp ms Int64, OHLCV Float32)}`` — sorting
    the old contract so ``screen.load_universe`` works unchanged.
    """
    if exchange != "binance":
        raise ValueError(f"unsupported exchange: {exchange} (only binance)")
    if tf not in _BAR_MS:
        raise ValueError(f"unsupported tf: {tf} (15m/30m/1h/4h/12h/1d)")
    sm, em = _ms(start), _ms(end) + 86_399_999
    data: dict[str, pl.DataFrame] = {}
    missing = []
    for canon in symbols(syms):
        path = _cache_path(_api(canon))
        if not os.path.exists(path):
            missing.append(canon)
            continue
        df = pl.read_parquet(path).filter(
            (pl.col("timestamp") >= sm) & (pl.col("timestamp") <= em)
        )
        if df.is_empty():
            continue
        df = _resample(df, tf, drop_partial)
        if df.height >= MIN_ROWS:
            data[canon] = df
    if missing:
        print(
            f"  {len(missing)} symbols have no cache "
            f"(e.g. {missing[0]}) — run --sync/--update first",
            file=sys.stderr,
        )
    return data


def coverage_report(data: dict[str, pl.DataFrame]) -> None:
    """Per-month symbol + row counts — verify a window is fully covered."""
    all_rows = []
    for sym, df in data.items():
        all_rows.append(
            pl.DataFrame({"sym": [sym] * df.height, "ts": df["timestamp"].to_numpy()})
        )
    if not all_rows:
        print("  (empty universe)", file=sys.stderr)
        return
    big = pl.concat(all_rows)
    cov = (
        big.with_columns(
            pl.from_epoch(pl.col("ts"), time_unit="ms")
            .dt.strftime("%Y-%m")
            .alias("month")
        )
        .group_by(["month", "sym"])
        .len()
        .group_by("month")
        .agg(pl.len().alias("syms"), pl.col("len").sum().alias("rows"))
        .sort("month")
    )
    for row in cov.iter_rows():
        print(
            f"  {row[0]}: {row[1]:3d} symbols, {row[2]:9,d} rows",
            file=sys.stderr,
        )


# ── CLI ─────────────────────────────────────────────────────────────────────


def main() -> None:
    import argparse

    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument(
        "--sync",
        action="store_true",
        help="full hydration: vision monthly backfill for missing months + REST tail",
    )
    g.add_argument(
        "--update",
        action="store_true",
        help="REST-only incremental tail refresh (daily maintenance)",
    )
    ap.add_argument(
        "--start", default="2023-01-01", help="backfill start (default 2023-01-01)"
    )
    ap.add_argument("--end", default=None, help="backfill end date (default: today)")
    ap.add_argument(
        "--universe",
        default=None,
        help="override universe file (default: config/symbols.yaml)",
    )
    args = ap.parse_args()

    end = args.end or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    hydrate_all(args.start, end, rest_only=args.update, universe=args.universe)


if __name__ == "__main__":
    main()
